"""reinit_migrations

Revision ID: 4a0ad49e2318
Revises: 
Create Date: 2026-02-13 16:37:07.332622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0ad49e2318'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('excel_task_items', 'new_share_url',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.Text(),
    #            existing_nullable=True)

    # 检查字段是否已存在，避免重复添加
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # 检查表是否存在，避免在全新安装时报错
    if inspector.has_table('excel_tasks'):
        columns = [col['name'] for col in inspector.get_columns('excel_tasks')]
        if 'target_channels' not in columns:
            op.add_column('excel_tasks', sa.Column('target_channels', sa.JSON(), nullable=True))

    # op.alter_column('link_history', 'share_link',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.Text(),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link_history', 'share_link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('excel_tasks', 'target_channels')
    op.alter_column('excel_task_items', 'new_share_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
