"""add interval to share push task

Revision ID: e478acc400f3
Revises: 028e5f2edb59
Create Date: 2026-03-22 18:58:26.143087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e478acc400f3'
down_revision: Union[str, Sequence[str], None] = '028e5f2edb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share_push_tasks', sa.Column('interval_min', sa.Integer(), server_default='3', nullable=False))
    op.add_column('share_push_tasks', sa.Column('interval_max', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('share_push_tasks', 'interval_max')
    op.drop_column('share_push_tasks', 'interval_min')
    # ### end Alembic commands ###
