services:
  p115-share:
    image: listeningltg/p115-share:latest
    container_name: p115-share
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  card-admin-web:
    build: ./frontend
    container_name: card-admin-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:18811:80"
    environment:
      TZ: Asia/Shanghai